name: github pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true 
          fetch-depth: 0  

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true

      # - uses: actions/cache@v2
      #   with:
      #     path: /tmp/hugo_cache
      #     key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-hugomod-

      - name: Get Hugo Modules
        run: hugo mod get -u

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'website'
          server: 'gate.sys-int.de'
          port: '222'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './public/*'
          remote_path: '/home/website/sites/marc-ende.de/'
          args: '-o ConnectTimeout=5'